qiniu:
  # Public key
  accessKey:
  # Private key
  secretKey:
  # Storage space name
  bucketName: 1binbin
  # Domain name/path
  path: http://rvw167yid.hn-bkt.clouddn.com
  # The file names stored in the space do not need to be deleted
  documentName: wyyMusic/


